# Secciones de arrays

_Hasta ahora sabemos cómo crear arrays y realizar algunas operaciones con ellos, sin embargo, todavía no hemos aprendido cómo acceder a elementos concretos del array_

In [1]:
import numpy as np

## Arrays de una dimensión

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Accediendo al primer elemento
arr[0] 

0

In [4]:
# Accediendo al último
arr[-1]

9

##### __¡Atención!__ 

NumPy devuelve __vistas__ de la sección que le pidamos, no __copias__. Esto quiere decir que debemos prestar mucha atención a este comportamiento:

In [5]:
arr = np.arange(10)
a = arr[5:]

print(arr)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]


In [6]:
arr[5] = 999

print(arr)
print(a)

[  0   1   2   3   4 999   6   7   8   9]
[999   6   7   8   9]


Lo mismo ocurre al revés:

In [7]:
arr = np.arange(10)
a = arr[5:]

print(arr)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]


In [8]:
a[-1] = 999

print(arr)
print(a)

[  0   1   2   3   4   5   6   7   8 999]
[  5   6   7   8 999]


`a` apunta a las direcciones de memoria donde están guardados los elementos del array `arr` que hemos seleccionado, no copia sus valores, a menos que explícitamente hagamos:

In [9]:
arr = np.arange(10)
a = arr[5:].copy()

print(arr)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]


In [10]:
arr[5] = 999

print(arr)
print(a)

[  0   1   2   3   4 999   6   7   8   9]
[5 6 7 8 9]


## Arrays de dos dimensiones

In [11]:
arr = np.arange(9).reshape([3, 3])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
arr[0, -1]

2

In [13]:
arr[2, 2]

8

## Secciones de arrays

Hasta ahora hemos visto cómo acceder a elementos aislados del array, pero la potencia de NumPy está en poder acceder a secciones enteras. Para ello se usa la sintaxis `inicio:final:paso`: si alguno de estos valores no se pone toma un valor por defecto. Veamos ejemplos:

In [14]:
M = np.arange(36, dtype=float).reshape(4, 9)
M

array([[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.],
       [  9.,  10.,  11.,  12.,  13.,  14.,  15.,  16.,  17.],
       [ 18.,  19.,  20.,  21.,  22.,  23.,  24.,  25.,  26.],
       [ 27.,  28.,  29.,  30.,  31.,  32.,  33.,  34.,  35.]])

In [15]:
# De la segunda a la tercera fila, incluida
M[1:3]

array([[  9.,  10.,  11.,  12.,  13.,  14.,  15.,  16.,  17.],
       [ 18.,  19.,  20.,  21.,  22.,  23.,  24.,  25.,  26.]])

In [16]:
# Hasta la tercera fila sin incluir y de la segunda a la quinta columnas saltando dos
M[:2, 1:5:2]
#M[1:2:1, 1:5:2]  # Equivalente

array([[  1.,   3.],
       [ 10.,  12.]])

##### Ejercicio

Pintar un tablero de ajedrez usando la función `plt.matshow`.
Ideas : Construir una matriz de 0 o de 1, pintar los 0 o 1 necesarios y aplicar la función correspondiente.

___Hemos aprendido:___

* A acceder a elementos de un array
* Que las secciones no devuelven copias, sino vistas

Algunos enlaces:

Algunos enlaces en Pybonacci:

* [Cómo crear matrices en Python con NumPy](http://pybonacci.wordpress.com/2012/06/11/como-crear-matrices-en-python-con-numpy/).
* [Números aleatorios en Python con NumPy y SciPy](http://pybonacci.wordpress.com/2013/01/11/numeros-aleatorios-en-python-con-numpy-y-scipy/).


Algunos enlaces en otros sitios:

* [100 numpy exercises](http://www.labri.fr/perso/nrougier/teaching/numpy.100/index.html). Es posible que de momento sólo sepas hacer los primeros, pero tranquilo, pronto sabrás más...
* [NumPy and IPython SciPy 2013 Tutorial](http://conference.scipy.org/scipy2013/tutorial_detail.php?id=100).
* [NumPy and SciPy documentation](http://docs.scipy.org/doc/).